- README.md
Öka läsbarheten genom lista m.m. Bytte även från "medborgare" till individ då vi även vill kunna serva de som inte är medborgare men bor i landet permanent
> Increase readability of readme

- operator/lib/routes/index.js
Create a /health route for use by orchestration platform.
> Create /health route

- examples/cv/package.json
test:
```bash
cd examples/cv
docker build -t meow .
```
> Re-add removed npm build command

- app/screens/Screen.js
- package.json
Also fixed a few linting errors
> Added npm command lint-all

- infrastructure/openshift/shared/app-BuildConfig.yml
- infrastructure/openshift/shared/app-ImageStream.yml
https://trello.com/c/bhJGB5qt/114-build-and-push-express-server-as-app-to-docker-hub
> Created buildconfig and imagestream for app

- infrastructure/openshift/ci/cv-DeploymentConfig.yml
- infrastructure/openshift/ci/operator-DeploymentConfig.yml
- infrastructure/openshift/test/cv-DeploymentConfig.yml
- infrastructure/openshift/test/operator-DeploymentConfig.yml
https://trello.com/c/ochanQrR/107-health-check-cv-ci
https://trello.com/c/B9MmYxyc/109-health-check-operator-ci
https://trello.com/c/803evmff/108-health-check-cv-test
https://trello.com/c/cNuf6Hf0/110-health-check-operator-test
> Added readiness- and livenessProbe to cv and operator deployments

- client/package-lock.json
- client/package.json
Released this to npm to get the patch from Gråborg out
> chore(client): increment @mydata/client version-number

- infrastructure/openshift/ci/operator-DeploymentConfig.yml
- infrastructure/openshift/test/operator-DeploymentConfig.yml
https://trello.com/c/VAYLVxWn/126-fix-appname-for-operator-test-and-operator-ci
> Updated APP_NAME for operator in ci and test respectively

- .travis.yml
https://trello.com/c/wmxns3JM/125-disable-lint-step-in-tag-build
> Add condition to not run lint when tag is present

- app/__e2e__/src/native/async-storage.js
- app/__e2e__/src/native/react-native.js
- app/__e2e__/webpack.config.js
- app/android/app/build.gradle
- app/android/app/src/main/java/work/mydata/MainApplication.java
- app/android/settings.gradle
- app/ios/MyData.xcodeproj/project.pbxproj
- app/jest.setup.js
- app/lib/services/__tests__/storage.test.js
- app/lib/services/storage.js
- app/package-lock.json
- app/package.json
https://trello.com/c/j9jmlwNE/176-fix-deprecation-warning-for-asyncstorage
Installed @react-native-community/async-storage
Replaced imports
Replaced mocks
> refactor(app): replace deprecated AsyncStorage

- .deliver-ci.bash
- .deliver-test.bash
- .travis.yml
> chore: devops improvements

- app/package.json
- client/package.json
- e2e/package.json
- examples/cv/package.json
- examples/national-registration/package.json
- operator/package.json
- mydata-phone-app@0.26.0
- @mydata/client@0.26.0
- mydata-e2e@0.26.0
- mydata-cv@0.26.0
- mydata-national-registration@0.26.0
- mydata-operator@0.26.0
> chore: Lerna publishing new version

- .travis.yml
- operator/Dockerfile
using root folder as context since we are using other folders as npm packages
> ci: 🎡 change operator build context

- infrastructure/openshift/legacy-operator/README.md
- infrastructure/openshift/legacy-operator/operator-DeploymentConfig.yml
- infrastructure/openshift/legacy-operator/operator-Route.yml
- infrastructure/openshift/legacy-operator/operator-Service.yml
- infrastructure/openshift/legacy-operator/postgresql-operator-DeploymentConfig.yml
- infrastructure/openshift/legacy-operator/postgresql-operator-Service.yml
- infrastructure/openshift/legacy-operator/redis-DeploymentConfig.yml
- infrastructure/openshift/legacy-operator/redis-Service.yml
it runs version 0.25.2 same as the current tag called latest-tag that runs on test
> chore: 🤖 locked version of operator compatible with myskills

- .travis.yml
now runs unit tests also
Closes: trello #250
https://trello.com/c/21VJtPVx/250-make-travis-run-unit-tests-again
> refactor: 💡 travis lint-and-test stage

- messaging/README
Added a README so outsiders will know what this module is for.
> doc: Create README for Messaging saying this is internal code-sharing module

- README.md
- app/README.md
- e2e/README.md
**Ticket:** [#259](https://trello.com/c/DKVUq608/259-update-readme-for-app)
**Intent:**
* Add more info about the most common mistake ppl make when running the app
* Add info about how to run tests locally
* Remove obsolete instructions about hosts-file (which currently is not used)
> docs: app update README with more gotcha about operator url

- package-lock.json
- package.json
**Ticket:** [#](TRELLOURL)
**Intent:**
Update Lerna version to a version without critical vulnerabilites
> chore: Update lerna

- client/lib/keyProvider.js
**Ticket:** [#271](https://trello.com/c/BA9ENp54/271)
**Intent:**
Remove useless escaping and eslint disabling
> chore: Remove useless escape

- app/__e2e__/src/native/react-native-simple-crypto.js
- app/__e2e__/webpack.config.js
- app/ios/Egendata.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist
- app/ios/Egendata.xcworkspace/xcshareddata/WorkspaceSettings.xcsettings
- app/ios/Podfile.lock
- app/lib/__mocks__/@egendata/react-native-simple-crypto.js
- app/lib/services/crypto.js
- app/package-lock.json
- app/package.json
**Ticket:** [#272](https://trello.com/c/vCkTRv0b/272-take-ownership-of-react-native-simple-crypto)
**Intent:**
Take control of crypto lib used in phone app
> refactor: Switched to @egendata version of crypto lib
